# Generated by Django 2.0 on 2018-12-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('expense_image', models.FileField(upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
